[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = [
    "pip install -r requirements.txt",
    "cd frontend && npm install && npm run build:prod"
]

[phases.build]
cmds = [
    "python manage.py collectstatic --noinput"
]

[start]
cmd = "python manage.py migrate && waitress-serve --host=0.0.0.0 --port=$PORT todofast.wsgi:application"
