[phases.setup]
nixPkgs = ["python311", "nodejs_20"]

[phases.install]
cmds = ["python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"]

[phases.build]
cmds = ["chmod +x build.sh && ./build.sh"]

[start]
cmd = "python manage.py migrate && waitress-serve --host=0.0.0.0 --port=$PORT todofast.wsgi:application"
