# Generated by Django 5.0.14 on 2025-09-08 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='שם התווית')),
                ('color', models.CharField(default='#808080', max_length=7, verbose_name='צבע')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='נוצר בתאריך')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to=settings.AUTH_USER_MODEL, verbose_name='בעלים')),
            ],
            options={
                'verbose_name': 'תווית',
                'verbose_name_plural': 'תוויות',
                'ordering': ['name'],
                'unique_together': {('name', 'owner')},
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='שם הפרויקט')),
                ('description', models.TextField(blank=True, verbose_name='תיאור')),
                ('color', models.CharField(choices=[('#DB4035', 'אדום'), ('#FF9933', 'כתום'), ('#FAD000', 'צהוב'), ('#7ECC49', 'ירוק'), ('#299438', 'ירוק כהה'), ('#6ACCBC', 'טורקיז'), ('#158FAD', 'כחול'), ('#14AAF5', 'כחול בהיר'), ('#96C3EB', 'כחול פסטל'), ('#4073FF', 'כחול רויאל'), ('#884DFF', 'סגול'), ('#AF38EB', 'סגול בהיר'), ('#EB96EB', 'ורוד'), ('#E05194', 'ורוד כהה'), ('#FF8D85', 'אדום בהיר'), ('#808080', 'אפור')], default='#DB4035', max_length=7, verbose_name='צבע')),
                ('is_team_project', models.BooleanField(default=False, verbose_name='פרויקט צוות')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='מועדף')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='נוצר בתאריך')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='עודכן בתאריך')),
                ('members', models.ManyToManyField(blank=True, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='חברים')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL, verbose_name='בעלים')),
            ],
            options={
                'verbose_name': 'פרויקט',
                'verbose_name_plural': 'פרויקטים',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='כותרת')),
                ('description', models.TextField(blank=True, verbose_name='תיאור')),
                ('priority', models.IntegerField(choices=[(1, 'נמוכה'), (2, 'בינונית'), (3, 'גבוהה'), (4, 'דחופה')], default=1, verbose_name='עדיפות')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='תאריך יעד')),
                ('due_time', models.TimeField(blank=True, null=True, verbose_name='שעת יעד')),
                ('is_completed', models.BooleanField(default=False, verbose_name='הושלמה')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='הושלמה בתאריך')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='חוזרת')),
                ('recurring_pattern', models.CharField(blank=True, max_length=100, verbose_name='תבנית חזרה')),
                ('order', models.IntegerField(default=0, verbose_name='סדר')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='נוצר בתאריך')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='עודכן בתאריך')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='מוקצה ל')),
                ('labels', models.ManyToManyField(blank=True, to='todo.label', verbose_name='תוויות')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='בעלים')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='todo.project', verbose_name='פרויקט')),
            ],
            options={
                'verbose_name': 'משימה',
                'verbose_name_plural': 'משימות',
                'ordering': ['order', '-priority', 'due_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='תוכן')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='נוצר בתאריך')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='עודכן בתאריך')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='מחבר')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='todo.task', verbose_name='משימה')),
            ],
            options={
                'verbose_name': 'הערה',
                'verbose_name_plural': 'הערות',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'בהיר'), ('dark', 'כהה')], default='light', max_length=10, verbose_name='ערכת נושא')),
                ('language', models.CharField(default='he', max_length=10, verbose_name='שפה')),
                ('timezone', models.CharField(default='Asia/Jerusalem', max_length=50, verbose_name='אזור זמן')),
                ('date_format', models.CharField(default='DD/MM/YYYY', max_length=20, verbose_name='פורמט תאריך')),
                ('start_of_week', models.IntegerField(default=0, verbose_name='תחילת השבוע')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='משתמש')),
            ],
            options={
                'verbose_name': 'פרופיל משתמש',
                'verbose_name_plural': 'פרופילי משתמשים',
            },
        ),
    ]
