# Generated by Django 5.0.14 on 2025-09-21 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_add_avatar_to_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='טוקן')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='נוצר בתאריך')),
                ('expires_at', models.DateTimeField(verbose_name='פג תוקף בתאריך')),
                ('is_used', models.BooleanField(default=False, verbose_name='בשימוש')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='נוצל בתאריך')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='כתובת IP')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verifications', to=settings.AUTH_USER_MODEL, verbose_name='משתמש')),
            ],
            options={
                'verbose_name': 'אימות אימייל',
                'verbose_name_plural': 'אימותי אימייל',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='todo_emailv_token_515d43_idx'), models.Index(fields=['user', 'is_used'], name='todo_emailv_user_id_a63b7a_idx'), models.Index(fields=['expires_at'], name='todo_emailv_expires_bcb51f_idx')],
            },
        ),
    ]
