# Generated by Django 5.0.14 on 2025-09-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_time_login',
            field=models.BooleanField(default=True, verbose_name='התחברות ראשונה'),
        ),
    ]
