# Generated by Django 5.0.14 on 2025-10-07 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_friend_invitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='googlecalendartoken',
            name='last_sync_time',
            field=models.DateTimeField(blank=True, help_text='Last successful sync timestamp', null=True),
        ),
        migrations.AddField(
            model_name='googlecalendartoken',
            name='last_sync_token',
            field=models.TextField(blank=True, help_text='Token for incremental sync', null=True),
        ),
        migrations.CreateModel(
            name='GoogleCalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_event_id', models.CharField(max_length=255, unique=True)),
                ('calendar_id', models.CharField(max_length=255)),
                ('calendar_summary', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_all_day', models.BooleanField(default=False)),
                ('html_link', models.URLField(blank=True, null=True)),
                ('color_id', models.CharField(blank=True, max_length=50, null=True)),
                ('event_data', models.JSONField(default=dict, help_text='Full event data from Google API')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cached_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Google Calendar Event',
                'verbose_name_plural': 'Google Calendar Events',
                'indexes': [models.Index(fields=['user', 'start_time'], name='todo_google_user_id_a86508_idx'), models.Index(fields=['google_event_id'], name='todo_google_google__f79a67_idx'), models.Index(fields=['calendar_id'], name='todo_google_calenda_538c9d_idx')],
            },
        ),
    ]
