# Generated by Django 5.0.14 on 2025-10-07 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_googlecalendartoken_last_sync_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlecalendartoken',
            name='sync_tokens',
            field=models.JSONField(default=dict, help_text='Per-calendar sync tokens'),
        ),
    ]
