# Generated by Django 5.0.14 on 2025-10-12 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0013_googlecalendartoken_sync_tokens'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('project_share', 'שיתוף פרויקט'), ('project_accepted', 'פרויקט התקבל'), ('project_declined', 'פרויקט נדחה'), ('member_left', 'חבר עזב'), ('general', 'כללי')], default='general', max_length=20, verbose_name='סוג התראה')),
                ('title', models.CharField(max_length=200, verbose_name='כותרת')),
                ('message', models.TextField(verbose_name='הודעה')),
                ('is_read', models.BooleanField(default=False, verbose_name='נקראה')),
                ('action_data', models.JSONField(blank=True, null=True, verbose_name='מידע לפעולה')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='נוצר בתאריך')),
                ('related_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.project', verbose_name='פרויקט קשור')),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_sender', to=settings.AUTH_USER_MODEL, verbose_name='משתמש קשור')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='משתמש')),
            ],
            options={
                'verbose_name': 'התראה',
                'verbose_name_plural': 'התראות',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='todo_notifi_user_id_d87944_idx'), models.Index(fields=['created_at'], name='todo_notifi_created_ced999_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'ממתין'), ('accepted', 'התקבל'), ('declined', 'נדחה')], default='pending', max_length=10, verbose_name='סטטוס')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='נוצר בתאריך')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='התקבל בתאריך')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='todo.project', verbose_name='פרויקט')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_projects', to=settings.AUTH_USER_MODEL, verbose_name='שותף על ידי')),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_shares', to=settings.AUTH_USER_MODEL, verbose_name='שותף עם')),
            ],
            options={
                'verbose_name': 'שיתוף פרויקט',
                'verbose_name_plural': 'שיתופי פרויקטים',
                'ordering': ['-created_at'],
                'unique_together': {('project', 'shared_with')},
            },
        ),
    ]
